version: "3.3"
services:
  db-tests:
    container_name: db-tests
    build:
      context: .
      dockerfile: code/jvm/tests/Dockerfile-db-test
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=changeit
      - POSTGRES_DB=db
    ports:
      - "5432:5432"

  # We will use docker compose scaling to create multiple instances of this service
  spring-service:
    build:
      context: .
      dockerfile: code/jvm/tests/Dockerfile-spring
    environment:
      PORT: 8080
      DB_URL: "jdbc:postgresql://db-tests:5432/db?user=dbuser&password=changeit"


  # The service running the load-balancer
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: code/jvm/tests/Dockerfile-nginx
    ports:
      - 8080:8080
      - 8088:8088

  # Just a machine running ubuntu, with 'dig' installed so that we can observe the docker compose environment.
  ubuntu:
    container_name: ubuntu
    build:
      context: .
      dockerfile: code/jvm/tests/Dockerfile-ubuntu
    tty: true