version: "3.3"
services:
  db-tests:
    container_name: db-tests
    build:
      context: .
      dockerfile: code/jvm/tests/Dockerfile-db-test
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=changeit
      - POSTGRES_DB=db
    ports:
      - "5432:5432"

  # spring-service-1 and spring-service-2 are used to illustrate scenarios with a fixed number of servers
  # with static and well know names.
  spring-service-1:
    container_name: spring-service-1
    hostname: spring-service-1
    build:
      context: .
      dockerfile: code/jvm/tests/Dockerfile-spring
    environment:
      PORT: 8081
      DB_URL: "jdbc:postgresql://db-tests:5432/db?user=dbuser&password=changeit"
    ports:
      - 8081:8081

  # The service running the load-balancer
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: code/jvm/tests/Dockerfile-nginx
    ports:
      - 8080:8080
      - 8088:8088
    depends_on:
      - spring-service-1

  # Just a machine running ubuntu, with 'dig' installed so that we can observe the docker compose environment.
  ubuntu:
    container_name: ubuntu
    build:
      context: .
      dockerfile: code/jvm/tests/Dockerfile-ubuntu
    tty: true