# Do the build process in multiple stages to reduce the size of the final image
FROM node:alpine as build

WORKDIR /app

# Install dependencies
COPY code/js/package.json  ./

RUN npm install

# Copy the source code
COPY code/js/src/ ./src

# Copy the configuration files
COPY code/js/.prettierrc \
        code/js/tsconfig.json \
        code/js/webpack.config.js \
        code/js/public/index.html \
        code/js/.eslintrc.json ./

RUN npm run build

FROM nginx:alpine
COPY code/jvm/tests/nginx/nginx.conf /etc/nginx/

# Copy the compiled application to the nginx directory
# Using the intermediate build stage
COPY --from=build /app/dist/main.js /opt/isel/daw/app/
COPY  --from=build /app/index.html /opt/isel/daw/app/